"""AI Coach — short training tips generated by a local Llama model.

Ollama is expected to run as a bare process on the host (not in a
container) and expose its HTTP API at OLLAMA_HOST. When it is
unreachable, times out, or returns something unusable, callers get
a static fallback tip instead of an error — the rest of the app
never depends on Llama being up.
"""

from __future__ import annotations

import os

import httpx

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.2")
REQUEST_TIMEOUT_SECONDS = 8.0

FALLBACK_TIP = "Сфокусируйся на технике сегодня — качество важнее скорости."


def build_prompt(focus: str, level: str) -> str:
    """Construct the coaching prompt sent to the model."""
    return (
        "Ты — тренер по плаванию. Дай один короткий (1-2 предложения) "
        "совет пловцу перед тренировкой, на русском языке.\n"
        f"Фокус тренировки: {focus}\n"
        f"Уровень пловца: {level}\n"
        "Совет:"
    )


def generate_tip(
    focus: str,
    level: str,
    client: httpx.Client | None = None,
) -> dict[str, str]:
    """Ask the local Llama model for a coaching tip.

    Returns {"tip": str, "source": "llama" | "fallback"}. Never
    raises — any transport error, timeout, or malformed response
    falls back to FALLBACK_TIP.
    """
    owns_client = client is None
    http_client = client or httpx.Client(timeout=REQUEST_TIMEOUT_SECONDS)
    try:
        response = http_client.post(
            f"{OLLAMA_HOST}/api/generate",
            json={
                "model": OLLAMA_MODEL,
                "prompt": build_prompt(focus, level),
                "stream": False,
            },
        )
        response.raise_for_status()
        text = response.json().get("response", "").strip()
        if text:
            return {"tip": text, "source": "llama"}
        return {"tip": FALLBACK_TIP, "source": "fallback"}
    except (httpx.HTTPError, ValueError, KeyError):
        return {"tip": FALLBACK_TIP, "source": "fallback"}
    finally:
        if owns_client:
            http_client.close()


def is_available(client: httpx.Client | None = None) -> bool:
    """Check whether the local Ollama server is reachable."""
    owns_client = client is None
    http_client = client or httpx.Client(timeout=2.0)
    try:
        response = http_client.get(f"{OLLAMA_HOST}/api/tags")
        return response.status_code == 200
    except httpx.HTTPError:
        return False
    finally:
        if owns_client:
            http_client.close()
